name: Tag Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Select the semantic version component to increment
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Determine next version
        id: version
        shell: bash
        run: |
          set -euo pipefail
          latest_tag="$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*' --sort=-version:refname | head -n 1)"
          if [ -z "$latest_tag" ]; then
            latest_tag="v0.0.0"
          fi

          version="${latest_tag#v}"
          IFS='.' read -r major minor patch <<< "$version"

          case "${{ github.event.inputs.release_type }}" in
            major)
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor + 1))
              patch=0
              ;;
            patch)
              patch=$((patch + 1))
              ;;
          esac

          new_tag="v${major}.${minor}.${patch}"
          new_version="${major}.${minor}.${patch}"

          echo "latest=$latest_tag" >> "$GITHUB_OUTPUT"
          echo "tag=$new_tag" >> "$GITHUB_OUTPUT"
          echo "version=$new_version" >> "$GITHUB_OUTPUT"

      - name: Update Cargo.toml version
        run: |
          sed -i '0,/^version = ".*"$/s//version = "${{ steps.version.outputs.version }}"/' Cargo.toml

      - name: Commit version bump
        run: |
          git add Cargo.toml
          git commit -m "chore: bump version to ${{ steps.version.outputs.version }}"
          git push origin HEAD:${{ github.ref }}

      - name: Create annotated tag
        run: |
          git tag -a "${{ steps.version.outputs.tag }}" -m "Release ${{ steps.version.outputs.tag }}"

      - name: Push tag
        run: |
          git push origin "${{ steps.version.outputs.tag }}"
          echo "Tag ${{ steps.version.outputs.tag }} pushed successfully"
